version: "3.9"
services:
   rabbitmq:
     build: rabbitmq
     environment:
       - RABBITMQ_DEFAULT_USER=test
       - RABBITMQ_DEFAULT_PASS=test
     ports:
       - '15672:15672'
       - '5672:5672'

   backend:
     build: backend
     command: python3 main.py
     ports:
       - '80:80'

   servicedb:
     build: servicedb
     command: python main.py
     ports:
       - '8888'
   db:
     build: db
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=test
     ports:
       - '5466:5466'
