version: "3.9"
services:
   rabbitmq:
     build: rabbitmq
     environment:
       - RABBITMQ_DEFAULT_USER=test
       - RABBITMQ_DEFAULT_PASS=test
     ports:
       - '15672:15672'
       - '5672:5672'
       - '5671:5671'
       - '4369:4369'
   backend:
     build:
       context: /
       dockerfile: ./backend/Dockerfile
     #command: python main.py
     ports:
       - '80:80'

   servicedb:
     build: servicedb
     #command: python main.py
     ports:
       - '8080:8080'
   db:
     build: db
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=test
     ports:
       - '5432:5432'
