EXPOSE 8888

WORKDIR /servicedb


RUN apk add --no-cache gcc musl-dev linux-headers

RUN apt-get install libpq-dev python3-dev


COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD ["python3", "run"]
