# syntax=docker/dockerfile:1
FROM python:3.7-alpine
EXPOSE 8888

WORKDIR /backend


RUN apk add --no-cache gcc musl-dev linux-headers



COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD ["python3", "run"]
